/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dtos.UsuarioDTO;
import excepciones.NegocioException;
import interfaces.ICrudUsuarioBO;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import negocio.CrudUsuarioBO;

/**
 *
 * @author eljulls
 */
public class FrmAgregarContacto extends javax.swing.JFrame {

    ICrudUsuarioBO crud;
    UsuarioDTO contacto;
    UsuarioDTO usuarioIniciado;

    /**
     * Creates new form FrmEditarPerfil
     *
     * @param usuarioIniciado
     */
    public FrmAgregarContacto(UsuarioDTO usuarioIniciado) {
        initComponents();
        this.crud = new CrudUsuarioBO();
        this.contacto = new UsuarioDTO();
        this.usuarioIniciado = usuarioIniciado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imagenPerfiles1 = new utilerias.ImagenPerfiles();
        txtNombre = new javax.swing.JTextField();
        menuButton1 = new utilerias.MenuButton();
        bBuscarContacto = new utilerias.MenuButton();
        txtNumero = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 122, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        jButton1.setText("   Regresar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        jLabel1.setText("Agregar Contacto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenPerfiles1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/fotoDefault.png"))); // NOI18N
        jPanel2.add(imagenPerfiles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 160, 150));

        txtNombre.setText("Nombre");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 490, 50));

        menuButton1.setBackground(new java.awt.Color(246, 246, 246));
        menuButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuButton1.setText("Añadir Contacto");
        menuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(menuButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 187, 51));

        bBuscarContacto.setBackground(new java.awt.Color(246, 246, 246));
        bBuscarContacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bBuscarContacto.setText("Buscar Contacto");
        bBuscarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarContactoActionPerformed(evt);
            }
        });
        jPanel2.add(bBuscarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 187, 51));

        txtNumero.setText("Numero");
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 460, 50));

        txtNumero2.setText("Numero");
        txtNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 460, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void menuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButton1ActionPerformed

        if (usuarioIniciado == null) {
            JOptionPane.showMessageDialog(this, "El usuario no está correctamente inicializado.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nombre = txtNombre.getText().trim();
        String numero = txtNumero.getText().trim();

        if (nombre.isEmpty() || numero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {

            crud.agregarContactoUsuario(usuarioIniciado.getTelefono(), contacto.getTelefono());

            if (usuarioIniciado.getContactos() == null) {
                usuarioIniciado.setContactos(new ArrayList<>());
            }
            usuarioIniciado.getContactos().add(txtNombre.getText());

            JOptionPane.showMessageDialog(this, "Contacto añadido correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
           
            txtNombre.setText("");
            txtNumero.setText("");
        } catch (NegocioException ex) {
            Logger.getLogger(FrmAgregarContacto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error al añadir el contacto: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuButton1ActionPerformed

    private void bBuscarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarContactoActionPerformed
        try {
            contacto = crud.consultaPorTelefono(txtNumero.getText());

            if (contacto != null) {
                JOptionPane.showMessageDialog(this, "Contacto encontrado", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                String nombreCompleto = contacto.getNombres() + " " + contacto.getApellidoPaterno() + " " + contacto.getApellidoMaterno();
                txtNombre.setText(nombreCompleto);

                if (contacto.getImagenPerfil() != null && contacto.getImagenPerfil().getArchivoImagen() != null) {
                    byte[] imageData = contacto.getImagenPerfil().getArchivoImagen().getData();
                    ImageIcon imageIcon = new ImageIcon(imageData);
                    imagenPerfiles1.setImagen(imageIcon);
                } else {
                    imagenPerfiles1.setImagen(null);
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el contacto", "Error", JOptionPane.ERROR_MESSAGE);
                txtNombre.setText("");
                imagenPerfiles1.setImagen(null);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar el contacto", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bBuscarContactoActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilerias.MenuButton bBuscarContacto;
    private utilerias.ImagenPerfiles imagenPerfiles1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private utilerias.MenuButton menuButton1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumero2;
    // End of variables declaration//GEN-END:variables
}
