/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dtos.ImagenDTO;
import dtos.UsuarioDTO;
import excepciones.NegocioException;
import interfaces.ICrudImagenBO;
import interfaces.ICrudUsuarioBO;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import negocio.CrudImagenBO;
import negocio.CrudUsuarioBO;
import utilidades.GestorImagenesMongoDTO;

/**
 *
 * @author eljulls
 */
public class FrmAgregarFotoRegistro extends javax.swing.JFrame {

    /**
     * Imagen de perfil seleccionada.
     */
    private ImagenDTO imagenPerfil;
    private ICrudImagenBO crudImagen;
    private UsuarioDTO usuarioRegistrando;
    private ICrudUsuarioBO crud;
    private Icon imagenDefault;

    /**
     * Creates new form FrmAgregarFotoRegistro
     *
     * @param usuarioRegistrando
     */
    public FrmAgregarFotoRegistro(UsuarioDTO usuarioRegistrando) {
        setLocationRelativeTo(this);
        initComponents();
        this.crudImagen = new CrudImagenBO();
        this.crud = new CrudUsuarioBO();
        this.usuarioRegistrando = usuarioRegistrando;
        imagenDefault= new ImageIcon(getClass().getResource("/fotoDefault.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        imagenPerfiles2 = new utilerias.ImagenPerfiles();
        jPanel4 = new javax.swing.JPanel();
        bContinuar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 145, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anadir.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        imagenPerfiles2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/fotoDefault.png"))); // NOI18N
        jPanel2.add(imagenPerfiles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 124, 210, 210));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 170, 90));

        bContinuar.setBackground(new java.awt.Color(0, 145, 26));
        bContinuar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        bContinuar.setForeground(new java.awt.Color(255, 255, 255));
        bContinuar.setText("Continuar");
        bContinuar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        bContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bContinuarActionPerformed(evt);
            }
        });
        jPanel2.add(bContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 250, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel3.setText("¿Deseas Agregar una foto de perfil?");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MacBook Air - 1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bContinuarActionPerformed
        if (imagenPerfil == null) {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "No ha agregado una imagen. ¿Está seguro de que desea continuar sin agregar una imagen?",
                    "Confirmación",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (respuesta == JOptionPane.NO_OPTION) {
                return;
            }
        }

        try {
            if (imagenPerfil != null) {
                crudImagen.Guardar(imagenPerfil);
                usuarioRegistrando.setImagenPerfil(imagenPerfil);
            }

            crud.Guardar(usuarioRegistrando);
            new FrmLogin().setVisible(true);
            dispose();
        } catch (NegocioException ex) {
            Logger.getLogger(FrmAgregarFotoRegistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bContinuarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            this.elegirFotoPerfil();
        } catch (IOException ex) {
           imagenPerfiles2.setImagen(imagenDefault);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void elegirFotoPerfil() throws IOException  {
        String path = this.obtenerPath();
        
        File file = new File(path);
        this.imagenPerfil = GestorImagenesMongoDTO.crearImagen("perfil", file);
        Icon imageIcon = GestorImagenesMongoDTO.getImageIcon(this.imagenPerfil, GestorImagenesMongoDTO.SizeImage.MEDIUM);

    }

    private String obtenerPath() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar la imagen de perfil.");

        FileNameExtensionFilter imageFilter
                = new FileNameExtensionFilter(
                        "Image files",
                        "jpg", "jpeg", "png"
                );
        fileChooser.setFileFilter(imageFilter);

        int userSelection = fileChooser.showOpenDialog(null);

        if (userSelection == JFileChooser.APPROVE_OPTION) {

            return fileChooser.getSelectedFile().getAbsolutePath();
        } else {
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bContinuar;
    private utilerias.ImagenPerfiles imagenPerfiles2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
