/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dtos.UsuarioDTO;
import excepciones.NegocioException;
import interfaces.ICrudUsuarioBO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import negocio.CrudUsuarioBO;
import utilidades.Encriptador;

/**
 *
 * @author eljulls
 */
public class FrmEditarPerfil extends javax.swing.JFrame {

    UsuarioDTO usuarioIniciado;
    ICrudUsuarioBO crud;

    /**
     * Creates new form FrmEditarPerfil
     */
    public FrmEditarPerfil(UsuarioDTO usuarioIniciado) {
        initComponents();
        this.usuarioIniciado = usuarioIniciado;
        this.crud = new CrudUsuarioBO();

        jLabel2.setText(usuarioIniciado.getTelefono());
        txtNombres.setText(usuarioIniciado.getNombres());
        txtApellidoP.setText(usuarioIniciado.getApellidoPaterno());
        txtApellidoM.setText(usuarioIniciado.getApellidoMaterno());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imagenPerfiles1 = new utilerias.ImagenPerfiles();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtContraseña1 = new javax.swing.JPasswordField();
        txtContraseña2 = new javax.swing.JPasswordField();
        txtGuardarCambios = new utilerias.MenuButton();
        bCambiarContraseña = new utilerias.MenuButton();
        cbMostrarContraseña = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 122, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        jButton1.setText("   Regresar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        jLabel1.setText("Editar Perfil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(196, 196, 196)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)))
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenPerfiles1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/fotoDefault.png"))); // NOI18N
        jPanel2.add(imagenPerfiles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 160, 150));

        jLabel2.setText("Numero Telefonico");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 430, 60));

        txtApellidoP.setText("Apellido Paterno");
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 240, 50));

        txtApellidoM.setText("Apellido Materno");
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 240, 50));

        txtNombres.setText("Nombre");
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 50));

        txtContraseña1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContraseña1.setForeground(new java.awt.Color(153, 153, 153));
        txtContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseña1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 240, 50));

        txtContraseña2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContraseña2.setForeground(new java.awt.Color(153, 153, 153));
        txtContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseña2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 240, 50));

        txtGuardarCambios.setText("Guardar Cambios");
        txtGuardarCambios.setBackground(new java.awt.Color(246, 246, 246));
        txtGuardarCambios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardarCambiosActionPerformed(evt);
            }
        });
        jPanel2.add(txtGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 187, 51));

        bCambiarContraseña.setText("Cambiar Contraseña");
        bCambiarContraseña.setBackground(new java.awt.Color(246, 246, 246));
        bCambiarContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCambiarContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(bCambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 187, 51));

        cbMostrarContraseña.setText("ver");
        cbMostrarContraseña.setToolTipText("");
        cbMostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMostrarContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(cbMostrarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 70, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseña2ActionPerformed

    private void txtContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseña1ActionPerformed

    private void txtGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardarCambiosActionPerformed
        try {
            UsuarioDTO actualizado = crud.consultaPorTelefono(usuarioIniciado.getTelefono());

            String nuevoNombre = txtNombres.getText().trim();
            String nuevoApellidoP = txtApellidoP.getText().trim();
            String nuevoApellidoM = txtApellidoM.getText().trim();

            // Actualizar el usuarioIniciado con los nuevos valores
            actualizado.setNombres(nuevoNombre);
            actualizado.setApellidoPaterno(nuevoApellidoP);
            actualizado.setApellidoMaterno(nuevoApellidoM);

            // Aquí podrías llamar a algún método para guardar en la base de datos o hacer algún otro procesamiento necesario
            // Por ejemplo:
            try {
                crud.Actualizar(actualizado);
                JOptionPane.showMessageDialog(this, "Perfil actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this, "Error al actualizar el perfil.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Opcionalmente, podrías cerrar el formulario después de guardar los cambios
            // this.dispose();
        } catch (NegocioException ex) {
            Logger.getLogger(FrmEditarPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Opcionalmente, podrías cerrar el formulario después de guardar los cambios
        // this.dispose();        
    }//GEN-LAST:event_txtGuardarCambiosActionPerformed

    private char[] solicitarContraseña() {
        JPasswordField passwordField = new JPasswordField();
        Object[] message = {
            "Ingrese su contraseña actual:", passwordField
        };
        int option = JOptionPane.showConfirmDialog(this, message, "Verificación de Contraseña", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (option == JOptionPane.OK_OPTION) {
            return passwordField.getPassword();
        } else {
            return null; // Usuario canceló la operación
        }
    }

    private boolean verificarContraseñaActual(String contraseñaActualEncriptada) {
        char[] contraseñaIngresada = solicitarContraseña();
        if (contraseñaIngresada == null) {
            return false; // Usuario canceló la operación
        }
        return Encriptador.verificarPasswordConHash(new String(contraseñaIngresada), contraseñaActualEncriptada);
    }

    private void bCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCambiarContraseñaActionPerformed
        if (verificarContraseñaActual(usuarioIniciado.getContrasena())) {
            String nuevaContraseña = txtContraseña1.getText();
            String confirmaNuevaContraseña = txtContraseña2.getText();

            if (nuevaContraseña == null || nuevaContraseña.isEmpty()) {
                JOptionPane.showMessageDialog(this, "La nueva contraseña no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!nuevaContraseña.equals(confirmaNuevaContraseña)) {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden. Por favor, inténtelo de nuevo.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                usuarioIniciado.setContrasena(nuevaContraseña);
                System.out.println("Nueva contraseña antes de encriptar: " + nuevaContraseña);
                crud.Actualizar(usuarioIniciado);
                JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (NegocioException ex) {
                Logger.getLogger(FrmEditarPerfil.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error al actualizar la contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "La contraseña actual ingresada es incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bCambiarContraseñaActionPerformed

    private void cbMostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMostrarContraseñaActionPerformed
        if (cbMostrarContraseña.isSelected()) {
            txtContraseña1.setEchoChar((char) 0);
            txtContraseña2.setEchoChar((char) 0);
        } else {
            txtContraseña1.setEchoChar('*');
            txtContraseña2.setEchoChar('*');
        }
    }//GEN-LAST:event_cbMostrarContraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilerias.MenuButton bCambiarContraseña;
    private javax.swing.JCheckBox cbMostrarContraseña;
    private utilerias.ImagenPerfiles imagenPerfiles1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JPasswordField txtContraseña1;
    private javax.swing.JPasswordField txtContraseña2;
    private utilerias.MenuButton txtGuardarCambios;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
