/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dtos.ChatDTO;
import dtos.UsuarioDTO;
import excepciones.NegocioException;
import interfaces.ICrudChatBO;
import interfaces.ICrudUsuarioBO;
import interfaces.IPusheaChatBO;
import interfaces.IVerificaChatExistenteBO;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.CrudChatBO;
import negocio.CrudUsuarioBO;
import negocio.PusheaChatBO;
import negocio.VerificaChatExistenteBO;
import utilerias.Dialogos;

/**
 *
 * @author eljulls
 */
public class FrmMain extends javax.swing.JFrame {

    private UsuarioDTO usuarioIniciado;
    private ICrudUsuarioBO crudUsuario;
    private ICrudChatBO crudChat;
    private IPusheaChatBO pushChat;
    private IVerificaChatExistenteBO chatExistente;

    /**
     * Creates new form FrmMain
     *
     * @param usuarioIniciado
     */
    public FrmMain(UsuarioDTO usuarioIniciado) {
        initComponents();
        this.usuarioIniciado = usuarioIniciado;
        this.crudUsuario = new CrudUsuarioBO();
        this.chatExistente = new VerificaChatExistenteBO();
        this.crudChat = new CrudChatBO();
        this.pushChat = new PusheaChatBO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelHome1 = new forms.JPanelHome();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHome1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoChat() {
        String telefono = Dialogos.pedirInputUsuario(
                rootPane,
                "Ingresa usuario",
                "Usuario"
        );

        if (telefono.equals(usuarioIniciado.getTelefono())) {
            Dialogos.mostrarMensajeError(
                    rootPane,
                    "No puedes hablar contigo mismo."
            );
            return;
        }

        try {
            UsuarioDTO usuarioReceptor = crudUsuario.consultaPorTelefono(telefono);

            if (usuarioReceptor == null) {
                Dialogos.mostrarMensajeError(rootPane, "No existe ese usuario.");
                return;
            }
            String idUsuarioReceptor = usuarioReceptor.getId();
            String idUsuarioLoggeado = usuarioIniciado.getId();

            boolean existeChat = chatExistente.verificarChatExistente(idUsuarioLoggeado, idUsuarioReceptor);
            if (existeChat) {
                Dialogos.mostrarMensajeError(rootPane, "Chat ya existe");
                return;
            }

            ChatDTO chat = new ChatDTO();
            chat.setEmisor(usuarioIniciado.getId());
            chat.setReceptor(usuarioReceptor.getId());
            chat.setFecha(LocalDateTime.now());

            crudChat.Guardar(chat);

            pushChat.pusheaChat(usuarioReceptor.getId(), chat.getId());
            pushChat.pusheaChat(usuarioIniciado.getId(), chat.getId());
        } catch (NegocioException e) {
            Dialogos.mostrarMensajeError(rootPane, "Error al crear el chat, intentelo denuevo");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private forms.JPanelHome jPanelHome1;
    // End of variables declaration//GEN-END:variables
}
