/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import dtos.UsuarioDTO;

/**
 *
 * @author Chris
 */
public class FrmPrincipalChats extends javax.swing.JFrame {
    private UsuarioDTO usuarioIniciado;

    /**
     * Creates new form FrmPrincipalChats
     */
    public FrmPrincipalChats(UsuarioDTO usuarioIniciado) {
        initComponents();
        this.usuarioIniciado = usuarioIniciado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background1 = new javax.swing.JPanel();
        pnListaChats1 = new javax.swing.JPanel();
        scPnChats1 = new javax.swing.JScrollPane();
        btnIniciaChat = new javax.swing.JButton();
        btnFiltrarChat = new javax.swing.JButton();
        pnChatActivo1 = new javax.swing.JPanel();
        txtNuevoMensaje1 = new javax.swing.JTextField();
        btnEnviar1 = new javax.swing.JButton();
        pnTituloChat1 = new javax.swing.JPanel();
        lblChatSeleccionado1 = new javax.swing.JLabel();
        fotoChatSeleccionado1 = new javax.swing.JLabel();
        scPnChatActivo1 = new javax.swing.JScrollPane();
        pnMsgsChat1 = new javax.swing.JPanel();
        lblContenidoChatInactivo1 = new javax.swing.JLabel();
        pnNavBar1 = new javax.swing.JPanel();
        btnPerfil1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background1.setBackground(new java.awt.Color(0, 0, 0));
        Background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnListaChats1.setBackground(new java.awt.Color(0, 0, 0));

        scPnChats1.setBackground(new java.awt.Color(51, 51, 51));
        scPnChats1.setForeground(new java.awt.Color(255, 255, 255));
        scPnChats1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scPnChats1MouseClicked(evt);
            }
        });

        btnIniciaChat.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnIniciaChat.setForeground(new java.awt.Color(0, 153, 153));
        btnIniciaChat.setText("Inicia chat");
        btnIniciaChat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciaChat.setBorderPainted(false);
        btnIniciaChat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIniciaChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciaChatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciaChatMouseExited(evt);
            }
        });
        btnIniciaChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaChatActionPerformed(evt);
            }
        });

        btnFiltrarChat.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnFiltrarChat.setForeground(new java.awt.Color(0, 153, 153));
        btnFiltrarChat.setText("Filtrar chats");
        btnFiltrarChat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFiltrarChat.setBorderPainted(false);
        btnFiltrarChat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFiltrarChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFiltrarChatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFiltrarChatMouseExited(evt);
            }
        });
        btnFiltrarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnListaChats1Layout = new javax.swing.GroupLayout(pnListaChats1);
        pnListaChats1.setLayout(pnListaChats1Layout);
        pnListaChats1Layout.setHorizontalGroup(
            pnListaChats1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnListaChats1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnListaChats1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scPnChats1)
                    .addGroup(pnListaChats1Layout.createSequentialGroup()
                        .addComponent(btnFiltrarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIniciaChat, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnListaChats1Layout.setVerticalGroup(
            pnListaChats1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnListaChats1Layout.createSequentialGroup()
                .addGroup(pnListaChats1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIniciaChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFiltrarChat, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scPnChats1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Background1.add(pnListaChats1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 450));

        pnChatActivo1.setBackground(new java.awt.Color(51, 51, 51));

        txtNuevoMensaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevoMensaje1ActionPerformed(evt);
            }
        });
        txtNuevoMensaje1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNuevoMensaje1KeyPressed(evt);
            }
        });

        btnEnviar1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnEnviar1.setForeground(new java.awt.Color(0, 153, 153));
        btnEnviar1.setText("Enviar");
        btnEnviar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEnviar1.setBorderPainted(false);
        btnEnviar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEnviar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnviar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnviar1MouseExited(evt);
            }
        });
        btnEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar1ActionPerformed(evt);
            }
        });

        pnTituloChat1.setBackground(new java.awt.Color(0, 0, 0));

        lblChatSeleccionado1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        fotoChatSeleccionado1.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout pnTituloChat1Layout = new javax.swing.GroupLayout(pnTituloChat1);
        pnTituloChat1.setLayout(pnTituloChat1Layout);
        pnTituloChat1Layout.setHorizontalGroup(
            pnTituloChat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloChat1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(lblChatSeleccionado1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(fotoChatSeleccionado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        pnTituloChat1Layout.setVerticalGroup(
            pnTituloChat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloChat1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTituloChat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTituloChat1Layout.createSequentialGroup()
                        .addComponent(lblChatSeleccionado1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fotoChatSeleccionado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnMsgsChat1.setBackground(new java.awt.Color(255, 255, 255));

        lblContenidoChatInactivo1.setText("Aqui se mostrara los mensajes con su contacto.");

        javax.swing.GroupLayout pnMsgsChat1Layout = new javax.swing.GroupLayout(pnMsgsChat1);
        pnMsgsChat1.setLayout(pnMsgsChat1Layout);
        pnMsgsChat1Layout.setHorizontalGroup(
            pnMsgsChat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMsgsChat1Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(lblContenidoChatInactivo1)
                .addContainerGap(348, Short.MAX_VALUE))
        );
        pnMsgsChat1Layout.setVerticalGroup(
            pnMsgsChat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMsgsChat1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(lblContenidoChatInactivo1)
                .addGap(121, 121, 121))
        );

        scPnChatActivo1.setViewportView(pnMsgsChat1);

        javax.swing.GroupLayout pnChatActivo1Layout = new javax.swing.GroupLayout(pnChatActivo1);
        pnChatActivo1.setLayout(pnChatActivo1Layout);
        pnChatActivo1Layout.setHorizontalGroup(
            pnChatActivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChatActivo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChatActivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChatActivo1Layout.createSequentialGroup()
                        .addComponent(txtNuevoMensaje1)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scPnChatActivo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnTituloChat1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnChatActivo1Layout.setVerticalGroup(
            pnChatActivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnChatActivo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnTituloChat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scPnChatActivo1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnChatActivo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuevoMensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Background1.add(pnChatActivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 710, 450));

        pnNavBar1.setBackground(new java.awt.Color(0, 145, 26));

        btnPerfil1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        btnPerfil1.setForeground(new java.awt.Color(0, 153, 153));
        btnPerfil1.setText("PERFIL");
        btnPerfil1.setBorder(null);
        btnPerfil1.setBorderPainted(false);
        btnPerfil1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPerfil1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfil1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfil1MouseExited(evt);
            }
        });
        btnPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfil1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnNavBar1Layout = new javax.swing.GroupLayout(pnNavBar1);
        pnNavBar1.setLayout(pnNavBar1Layout);
        pnNavBar1Layout.setHorizontalGroup(
            pnNavBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNavBar1Layout.createSequentialGroup()
                .addContainerGap(840, Short.MAX_VALUE)
                .addComponent(btnPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnNavBar1Layout.setVerticalGroup(
            pnNavBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNavBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPerfil1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Background1.add(pnNavBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scPnChats1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scPnChats1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_scPnChats1MouseClicked

    private void btnIniciaChatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciaChatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciaChatMouseEntered

    private void btnIniciaChatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciaChatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciaChatMouseExited

    private void btnIniciaChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciaChatActionPerformed

    private void btnFiltrarChatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarChatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarChatMouseEntered

    private void btnFiltrarChatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarChatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarChatMouseExited

    private void btnFiltrarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarChatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarChatActionPerformed

    private void txtNuevoMensaje1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNuevoMensaje1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoMensaje1KeyPressed

    private void btnEnviar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviar1MouseEntered

    private void btnEnviar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviar1MouseExited

    private void btnEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviar1ActionPerformed

    private void btnPerfil1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfil1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfil1MouseEntered

    private void btnPerfil1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfil1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfil1MouseExited

    private void btnPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfil1ActionPerformed

    private void txtNuevoMensaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoMensaje1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoMensaje1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background1;
    private javax.swing.JButton btnEnviar1;
    private javax.swing.JButton btnFiltrarChat;
    private javax.swing.JButton btnIniciaChat;
    private javax.swing.JButton btnPerfil1;
    private javax.swing.JLabel fotoChatSeleccionado1;
    private javax.swing.JLabel lblChatSeleccionado1;
    private javax.swing.JLabel lblContenidoChatInactivo1;
    private javax.swing.JPanel pnChatActivo1;
    private javax.swing.JPanel pnListaChats1;
    private javax.swing.JPanel pnMsgsChat1;
    private javax.swing.JPanel pnNavBar1;
    private javax.swing.JPanel pnTituloChat1;
    private javax.swing.JScrollPane scPnChatActivo1;
    private javax.swing.JScrollPane scPnChats1;
    private javax.swing.JTextField txtNuevoMensaje1;
    // End of variables declaration//GEN-END:variables
}
