/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import dtos.ImagenDTO;
import dtos.UsuarioDTO;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import utilerias.CargarFonts;

/**
 *
 * @author eljulls
 */
public class JPanelContacto extends javax.swing.JPanel {

    /**
     * Creates new form JPanelContacto
     */
    public JPanelContacto(UsuarioDTO contacto) {
        initComponents();
        aplicarFuentePersonalizada();
        metodosIniciales();
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNombre.setText(contacto.getNombres());
        Icon fotoPerfil = imagenDTOAIcon(contacto.getImagenPerfil());
        imagenPerfiles1.setImagen(fotoPerfil);
    }
    
    private void aplicarFuentePersonalizada() {
        Font fuente = CargarFonts.cargarFonts("src/main/resources/SF-Pro-Text-Medium.ttf"); // Asegúrate de que la ruta sea correcta
        if (fuente != null) {
            lblNombre.setFont(fuente.deriveFont(Font.PLAIN, 14)); // Ajusta el tamaño y el estilo de la fuente
        }
    }
    
    private void metodosIniciales() {
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent me) {
                setBackground(new Color(246, 246, 246));
            }
            
            @Override
            public void mouseExited(MouseEvent me) {
                setBackground(new Color(255, 255, 255));
            }
        });
    }
    
    private Icon imagenDTOAIcon(ImagenDTO imagenDTO) {
        try {
            byte[] imageData = imagenDTO.getArchivoImagen().getData();
            BufferedImage image = ImageIO.read(new ByteArrayInputStream(imageData));
            return new ImageIcon(image);
        } catch (IOException e) {
            // Handle the exception, e.g., log an error or return a default icon
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPerfiles1 = new utilerias.ImagenPerfiles();
        lblNombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        imagenPerfiles1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/prueba.jpg"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setText("Nombre Contacto");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contactoflecha.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenPerfiles1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagenPerfiles1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilerias.ImagenPerfiles imagenPerfiles1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
