/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import chat.JPanelChatAbajo;
import chat.JPanelChatArriba;
import chat.JPanelChatCuerpo;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author eljulls
 */
public class JPanelChats extends javax.swing.JPanel {

    JPanelChatArriba chatArriba;

    public JPanelChats() {
        initComponents();
        setLayout(new MigLayout("fillx", "0[fill]0", "0[]0[100%, bottom]0[shrink 0]0"));
        chatArriba = new JPanelChatArriba();
        JPanelChatAbajo chatAbajo = new JPanelChatAbajo();
        JPanelChatCuerpo chatCuerpo = new JPanelChatCuerpo();
        add(chatArriba, "wrap");
        add(chatCuerpo, "wrap");
        add(chatAbajo, "h ::50%");
    }

    public JButton getToggleButton() {
        return chatArriba.getButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1131, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

//    public JButton getToggleButton() {
//        rety//return toggleButton;
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
