/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chat;

import forms.JPanelChats;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JScrollBar;
import net.miginfocom.swing.MigLayout;
import utilerias.ScrollBar;

/**
 *
 * @author eljulls
 */
public class JPanelChatCuerpo extends javax.swing.JPanel {


    /**
     * Creates new form JPanelChatCuerpo
     */
    public JPanelChatCuerpo() {
        initComponents();
        metodosIniciales();
        mensajeIzquierdo("hola");
        mensajeDerecho("Como estasComo estassComo estassComo estassComo estassComo estassComo estassComo estassComo estasss");
        mensajeIzquierdo("brooooooooooooooooooooooooooooooo");
        mensajeDerecho("Como estasComo estassComo estassComo estassComo estassComo estassComo estassComo estassComo estasss");
        mensajeIzquierdo("brooooooooooooooooooooooooooooooo");
        mensajeDerecho("Como estasComo estassComo estassComo estassComo estassComo estassComo estassComo estassComo estasss");
        mensajeIzquierdo("brooooooooooooooooooooooooooooooo");
        mensajeDerecho("Como estasComo estassComo estassComo estassComo estassComo estassComo estassComo estassComo estasss");
        mensajeIzquierdo("brooooooooooooooooooooooooooooooo");
        mensajeDerecho("Como estasComo estassComo estassComo estassComo estassComo estassComo estassComo estassComo estasss");
        mensajeIzquierdo("brooooooooooooooooooooooooooooooo");
        mensajeDerecho("Como estasComo estassComo estassComo estassComo estassComo estassComo estassComo estassComo estasss");
        mensajeIzquierdo("brooooooooooooooooooooooooooooooo");
        mensajeDerecho("Como estasComo estassComo estassComo estassComo estassComo estassComo estassComo estassComo estasss");
        mensajeIzquierdo("brooooooooooooooooooooooooooooooo");
        mensajeDerecho("Como estasComo estassComo estassComo estassComo estassComo estassComo estassComo estassComo estasss");
        mensajeIzquierdo("brooooooooooooooooooooooooooooooo");

    }

    private void metodosIniciales() {
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        jPanel2.setLayout(new MigLayout("fillx","","2[]2"));
    }
    

    public void mensajeIzquierdo(String texto) {
        JPanelChatIzquierdo mensaje = new JPanelChatIzquierdo();
        mensaje.setTexto(texto);
        jPanel2.add(mensaje, "wrap, w ::80%");
        //  ::80% set max with 80%
        jPanel2.repaint();
        jPanel2.revalidate();
    }
    
       public void mensajeDerecho(String textk) {
        JPanelChatDerecho mensaje = new JPanelChatDerecho();
        mensaje.setTexto(textk);
        jPanel2.add(mensaje, "wrap, al right, w ::80%");
        //  ::80% set max with 80%
        jPanel2.repaint();
        jPanel2.revalidate();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 51, 51));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(239, 239, 244));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
