/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package chat;

/**
 *
 * @author eljulls
 */
public class JPanelMensaje extends javax.swing.JPanel {

    /**
     * Creates new form JPanelMensaje
     */
    public JPanelMensaje() {
        initComponents();
        txtMensaje.setEditable(false);
    }

    public void setTexto(String texto) {
        txtMensaje.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMensaje = new utilerias.JIMSendTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        txtMensaje.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtMensaje.setMinimumSize(new java.awt.Dimension(1, 1));
        add(txtMensaje);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilerias.JIMSendTextPane txtMensaje;
    // End of variables declaration//GEN-END:variables
}
